### ISSUE TITLE
Decoder panics

### ISSUE THREAD

**Issue by gediminasgu** [aler9/gomavlib#8]
I get a panic here https://github.com/aler9/gomavlib/blob/master/pkg/msg/decencoder.go#L397 when a plane goes into landing procedure. As it happens only when airborne (couldn't reproduce it on a simulator) it's hard to tell which message it was. Maybe someone will have an idea? I'm fine to write a test for it and send a PR. A quick workaround was changing that line to:
```
for end < len(buf) && buf[end] != 0 && end < int(f.arrayLength) {
```

The stack trace:
```
panic: runtime error: index out of range [50] with length 50

goroutine 60 [running]:
github.com/aler9/gomavlib.decodeValue(0x2f69c8, 0x200f374, 0x198, 0x2100281, 0x32, 0x32, 0x217cf20, 0x1)
	/home/user/go/pkg/mod/github.com/aler9/gomavlib@v0.0.0-20191214183340-7ef85c972f00/dialect.go:415 +0x74c
github.com/aler9/gomavlib.(*dialectMessage).decode(0x217cda0, 0x2100281, 0x32, 0x32, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/aler9/gomavlib@v0.0.0-20191214183340-7ef85c972f00/dialect.go:325 +0x258
github.com/aler9/gomavlib.(*Parser).Read(0x24ce1e0, 0x203efc4, 0x211d2a0, 0x0, 0x0)
	/home/user/go/pkg/mod/github.com/aler9/gomavlib@v0.0.0-20191214183340-7ef85c972f00/parser.go:305 +0x5d4
github.com/aler9/gomavlib.(*Channel).run.func1(0x20121c0, 0x20278c0)
	/home/user/go/pkg/mod/github.com/aler9/gomavlib@v0.0.0-20191214183340-7ef85c972f00/channel.go:73 +0xc4
created by github.com/aler9/gomavlib.(*Channel).run
	/home/user/go/pkg/mod/github.com/aler9/gomavlib@v0.0.0-20191214183340-7ef85c972f00/channel.go:65 +0x48
```

**Comment by aler9** [comment]
Hello, thanks for reporting the issue, this should be fixed in master. Please test and let me know if the fix works.
